highlighter: rouge
baseurl: /metaheuristics
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/jmp75/metaheuristics
# help_url: https://github.com/jekyll/help