<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Getting started with the 'mhpp' package}
-->

=================

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(out.extra='style="display:block; margin: auto"', fig.align="center", fig.width=10, fig.height=8, dev='png')
```

# About this document

This document was generated from an R markdown file on `r as.character(Sys.time())`. It illustrates how to set up a calibration on a time stepping model simulation.

```{r, eval=FALSE, include=FALSE}
library(swiftdev)
setwd(file.path('F:/src/github_jm/metaheuristics/R/pkgs/mh', 'vignettes'))
purlVignettes('.', '..')
```

# Getting started

```{r, eval=FALSE}
```

```{r, eval=FALSE}

# library(dplyr)

library(mhcpp)
create_hypercubes <- function(n, minima, maxima, pnames, seed) {
  if(!missing(seed)) set.seed(seed)
  values <- as.data.frame(sapply(1:length(minima), function(i) runif(n, minima[i], maxima[i])))
  names(values) <- pnames
  values
}

minima <- 1:3
pnames <- letters[minima]
names(minima) <- pnames
maxima <- 2:4
names(maxima) <- pnames
n <- 7

L2_distance <- function(observed, modelled) {
  d <- observed - modelled
  return(sqrt(sum(d*d)))
}

goal <- (maxima+minima)/2
objective_fct <- function(x){
  return(L2_distance(goal, x))
}

OF <- mhcpp::Objective
obj <- new( OF, objective_fct, "the obj", goal)

psets <- create_hypercubes(n, minima, maxima, pnames)
head(psets)

pop <- new( Population, psets, minima, maxima)

str(pop)

cx <- new(Complex, pop, obj, 5L, 0L)

cx$evolve()

s = cx$get_population()
s$as_dataframe()

```

